version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: 12 
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'dist/*'